import type { Product } from "@/types/product";

const now = new Date().toISOString();

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-1",
    name: "Aurora",
    slug: "aurora",
    description:
      "El modelo Aurora combina calce exclusivo con un diseño de autor. Acetato negro pulido, lineas precisas y caracter sobrio. Disponible en multiples colores.",
    short_description: "Recetado — Acetato negro",
    is_exclusive: true,
    materials: "Acetato italiano",
    lens_type: "recetado",
    available_colors: [
      { name: "Negro", hex: "#0A0A0A" },
      { name: "Carey", hex: "#5A3A1F" },
      { name: "Cristal", hex: "#E8E4DC" },
    ],
    category: "recetados",
    images: [],
    display_order: 1,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
  {
    id: "demo-2",
    name: "Eclipse",
    slug: "eclipse",
    description:
      "Redondo oversize en carey ambar. Un clasico reinterpretado con personalidad. Amplio stock en toda la gama de colores.",
    short_description: "Sol — Carey ambar",
    is_exclusive: true,
    materials: "Acetato italiano",
    lens_type: "sol",
    available_colors: [
      { name: "Ambar", hex: "#A86B2C" },
      { name: "Negro", hex: "#0A0A0A" },
    ],
    category: "sol",
    images: [],
    display_order: 2,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
  {
    id: "demo-3",
    name: "Zenith",
    slug: "zenith",
    description:
      "Marco de metal dorado con presencia minima. Para quienes prefieren la elegancia discreta.",
    short_description: "Sol — Metal dorado",
    is_exclusive: true,
    materials: "Titanio japones",
    lens_type: "sol",
    available_colors: [
      { name: "Dorado", hex: "#C4A265" },
      { name: "Plata", hex: "#C0C0C0" },
    ],
    category: "sol",
    images: [],
    display_order: 3,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
  {
    id: "demo-4",
    name: "Prism",
    slug: "prism",
    description:
      "Recetado en acetato bordo. Un toque de color sin perder la sobriedad.",
    short_description: "Recetado — Acetato bordo",
    is_exclusive: true,
    materials: "Acetato italiano",
    lens_type: "recetado",
    available_colors: [
      { name: "Bordo", hex: "#7A1F2C" },
      { name: "Negro", hex: "#0A0A0A" },
    ],
    category: "recetados",
    images: [],
    display_order: 4,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
  {
    id: "demo-5",
    name: "Nova",
    slug: "nova",
    description: "Recetado en acetato gris perla.",
    short_description: "Recetado — Acetato perla",
    is_exclusive: false,
    materials: "Acetato italiano",
    lens_type: "recetado",
    available_colors: [{ name: "Perla", hex: "#D4D0C8" }],
    category: "recetados",
    images: [],
    display_order: 5,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
  {
    id: "demo-6",
    name: "Onyx",
    slug: "onyx",
    description: "Sol en acetato negro mate.",
    short_description: "Sol — Acetato negro",
    is_exclusive: false,
    materials: "Acetato italiano",
    lens_type: "sol",
    available_colors: [{ name: "Negro mate", hex: "#1A1A1A" }],
    category: "sol",
    images: [],
    display_order: 6,
    seo_title: null,
    seo_description: null,
    created_at: now,
  },
];
