insert into site_content (key, value, page, section, label, field_type, sort_order) values
  ('home.hero.label', 'Modelaje exclusivo en armazones y anteojos de sol', 'home', 'hero', 'Etiqueta del hero', 'short_text', 1),
  ('home.hero.subtitle', 'Con enorme variedad de colores en todas sus lineas.', 'home', 'hero', 'Subtitulo del hero', 'short_text', 2),
  ('home.hero.cta', 'Escribinos por WhatsApp', 'home', 'hero', 'Texto boton CTA', 'short_text', 3),
  ('home.hero.subcta', 'Venta solo a mayoristas y distribuidores', 'home', 'hero', 'Texto sub-CTA', 'short_text', 4),
  ('home.exclusive.label', 'Oportunidades', 'home', 'exclusive', 'Etiqueta seccion exclusiva', 'short_text', 5),
  ('home.exclusive.title', 'Modelaje Exclusivo', 'home', 'exclusive', 'Titulo seccion exclusiva', 'short_text', 6),
  ('home.exclusive.description', 'Calce y diseno de autor. Armazones pensadas para perdurar, con materiales que resisten el paso del tiempo.', 'home', 'exclusive', 'Descripcion seccion exclusiva', 'long_text', 7),
  ('home.collection.label', 'Todos los modelos', 'home', 'collection', 'Etiqueta coleccion', 'short_text', 8),
  ('home.collection.title', 'Nuestra Coleccion', 'home', 'collection', 'Titulo coleccion', 'short_text', 9),
  ('home.brand.label', 'Solo Mayoristas', 'home', 'brand', 'Etiqueta brand statement', 'short_text', 10),
  ('home.brand.primary', 'Interesantes ofertas en modelos de temporadas pasadas. Colores variados y amplisimo stock disponible para grandes compradores.', 'home', 'brand', 'Texto principal', 'long_text', 11),
  ('home.brand.secondary', 'Mayoristas y distribuidores con muchos clientes y a la vanguardia de las nuevas tendencias. Consultanos por las opciones.', 'home', 'brand', 'Texto secundario', 'long_text', 12),
  ('home.cta.title', 'Escribinos por WhatsApp', 'home', 'cta', 'Titulo CTA final', 'short_text', 13),
  ('home.cta.description', 'Somos mayoristas. Oportunidades para grandes compradores con amplisimos stocks y colores variados en todas nuestras lineas.', 'home', 'cta', 'Descripcion CTA final', 'long_text', 14),

  ('about.hero.label', 'Sobre Warszawski', 'about', 'hero', 'Etiqueta hero', 'short_text', 1),
  ('about.hero.title', 'Diseno que habla por si mismo', 'about', 'hero', 'Titulo hero', 'short_text', 2),
  ('about.origin.title', 'Vision clara, estilo propio', 'about', 'origin', 'Titulo historia', 'short_text', 3),
  ('about.origin.p1', 'Warszawski nace de una pasion por el diseno optico de autor. Cada armazon responde a una busqueda constante de calce, proporcion y caracter.', 'about', 'origin', 'Parrafo 1', 'long_text', 4),
  ('about.origin.p2', 'Esa vision se traduce hoy en anteojos que combinan la rigurosidad del diseno con materiales de primera linea. No buscamos seguir tendencias. Buscamos crear objetos que perduren.', 'about', 'origin', 'Parrafo 2', 'long_text', 5),
  ('about.value1.title', 'Diseno con intencion', 'about', 'values', 'Valor 01 - Titulo', 'short_text', 6),
  ('about.value1.description', 'Cada modelo responde a una idea clara. Nada es arbitrario: la forma, el material, el color tienen un por que.', 'about', 'values', 'Valor 01 - Descripcion', 'long_text', 7),
  ('about.value2.title', 'Materiales nobles', 'about', 'values', 'Valor 02 - Titulo', 'short_text', 8),
  ('about.value2.description', 'Acetato italiano, titanio japones, lentes de primera calidad. Los materiales definen la experiencia tanto como el diseno.', 'about', 'values', 'Valor 02 - Descripcion', 'long_text', 9),
  ('about.value3.title', 'Atencion personal', 'about', 'values', 'Valor 03 - Titulo', 'short_text', 10),
  ('about.value3.description', 'No somos un carrito de compras. Te acompanamos en la eleccion, te asesoramos, y nos aseguramos de que el resultado sea perfecto.', 'about', 'values', 'Valor 03 - Descripcion', 'long_text', 11),
  ('about.cta.title', 'Queremos conocerte', 'about', 'cta', 'Titulo CTA', 'short_text', 12),
  ('about.cta.description', 'Escribinos por WhatsApp y charlemos sobre lo que estas buscando. Sin apuro, sin compromiso.', 'about', 'cta', 'Descripcion CTA', 'long_text', 13)
on conflict (key) do nothing;
